services:
  frontend:
    container_name: taic-frontend
    build: ./frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "3011:80"
    # command: "npm start"

  backend:
    container_name: taic-backend
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - 3012:80
  
  mysql_db:
    container_name: mysql_db_taic
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taic_app
    ports:
    - 3313:3306

  phpmyadmin:
    container_name: phpmyadmin_taic
    image: phpmyadmin:5.2.1
    ports:
      - 3014:80
    environment:
      - PMA_ARBITRARY=1